# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [4]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(size=(7, 7))

random_tensor

tensor([[0.6429, 0.1366, 0.8108, 0.3466, 0.5978, 0.4389, 0.4029],
        [0.9327, 0.9733, 0.6891, 0.3038, 0.6886, 0.0792, 0.0328],
        [0.4003, 0.9201, 0.8006, 0.0931, 0.0656, 0.2620, 0.2979],
        [0.0496, 0.7812, 0.8886, 0.5491, 0.5586, 0.3182, 0.6583],
        [0.5165, 0.1315, 0.8348, 0.9278, 0.0606, 0.6913, 0.9801],
        [0.6465, 0.9050, 0.6065, 0.8923, 0.3645, 0.0298, 0.5640],
        [0.1402, 0.9648, 0.0695, 0.7177, 0.8960, 0.8653, 0.4289]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [6]:
# Create another random tensor
another_random_tensor = torch.rand(size=(1, 7))

# Perform matrix multiplication 
result = torch.matmul(random_tensor, another_random_tensor.T)

result

tensor([[2.0112],
        [1.8289],
        [1.8915],
        [2.1230],
        [2.6732],
        [2.0073],
        [1.7249]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [7]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
A = torch.rand(size=(7, 7))
B = torch.rand(size=(1, 7))

# Matrix multiply tensors
result = torch.matmul(A, B.T)

result

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [8]:
# Set random seed on the GPU
torch.cuda.random.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [13]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
torch.cuda.is_available()
device = "cuda" if torch.cuda.is_available() else "cpu"
device

# Create two random tensors on GPU
A = torch.rand(size=(2, 3)).to(device)
B = torch.rand(size=(2, 3)).to(device)

print(A, A.device)
print(B, B.device)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0') cuda:0
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0') cuda:0



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [15]:
# Perform matmul on tensor_A and tensor_B
result = torch.matmul(A, B.T)
result

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [16]:
# Find max
max = result.max()

# Find min
min = result.min()

print("Max", max)
print("Min", min)

Max tensor(0.5617, device='cuda:0')
Min tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [18]:
# Find arg max
argmax = result.argmax()

# Find arg min
argmin = result.argmin()

print("argmax", argmax)
print("argmin", argmin)

argmax tensor(3, device='cuda:0')
argmin tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [21]:
# Set seed
torch.manual_seed(7)

# Create random tensor
C = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
C = torch.squeeze(C)

# Print out tensors and their shapes
print("C", C)
print("C.shape", C.shape)

C tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
C.shape torch.Size([10])
